---
apiVersion: v1
kind: ConfigMap
metadata:
  name: preprod-multibranch-pipeline-demo-application-config
  namespace: preprod
  labels:
    env: preprod
    app: multibranch-pipeline-demo-ms
    layer: frontend
data:
  application.properties: |-