apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: preprod-multibranch-pipeline-demo-hpa
  namespace: preprod
  labels:
    env: preprod
    app: multibranch-pipeline-demo-ms
    layer: frontend
spec:
  maxReplicas: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: preprod-multibranch-pipeline-demo-deployment
  targetCPUUtilizationPercentage: 80  